### PR TITLE
DAS-1701 - Remove leading slashes from requested variable names.

### PR DESCRIPTION
**Pull request by owenlittlejohns**
## Description

This PR accommodates recent changes to the UMM-Var records for collections hosted in the EEDTEST UAT provider. These collections have been updated to remove leading slashes from the UMM-Var `Name` attributes (e.g., `/BEAM0000/lat_lowestmode` has become `BEAM0000/lat_lowestmode`) **only for top-level variables**.

Update:

There has been a bit of back-and-forth on this in Slack. For the purposes of this ticket, I've _only_ updated top-level variables to remove the slash. This includes the MERRA-2 collections (M2T1NXSLV and M2I3NPASM), one of which is used in a test in this notebook. If it is determined, that all variable need to be updated, I'll conduct that work in a separate ticket, as this may have wider reaching implications for Harmony itself.

## Jira Issue ID

DAS-1701

## Local Test Steps

* Pull this branch of the repository.
* Start a Jupyter notebook server.
* Update the `harmony_host_url` in the first cell to point to SIT (SIT has a more up-to-date version of MaskFill, which passes a test. UAT doesn't have this version, yet).
* Run the tests.
* All should pass.

## PR Acceptance Checklist
* [x] Acceptance criteria met
* [x] Tests added/updated (if needed) and passing
* ~~Documentation updated (if needed)~~

### CODE REVIEW

**Comment by owenlittlejohns** [comment]
It's worth noting - since the variable names have already changed, the tests in this notebook that specify variables in their Harmony request will fail until this PR is merged.

**Comment by chris-durbin** [comment]
I don't really understand the rationale for the no trailing slash in variables and why a leading slash means different behavior for EDSC, but is this change in convention going to break existing services that expect the variable to match what is in the NetCDF-4 file? I'm just trying to figure out if we need to bring this up in the harmony channel to all of the providers.

**Comment by owenlittlejohns** [comment]
A quick recap of a longer Slack conversation. UVG-348 only intends to remove leading slashes from top-level variables. There are a couple of those that have been updated in CMR as part of DAS-1701 (e.g., MERRA-2), so this PR will be updated to only change those variables, once nested variables have had their slash restored.

**Comment by owenlittlejohns** [comment]
The second commit added to this PR only changes the top-level variable in the notebook. This is because I've reverted hierarchical variables to have a leading slash, while discussions are ongoing. Any changes to hierarchical variable names can be tracked in a separate ticket.

Regardless of the behaviour of hierarchical variables, it seems like the one consistent thing is that top-level variables should not have leading slashes, which is now the case for the EEDTEST collections.

**Review by flamingbear — APPROVED** [review]
Looks like you only removed the slash from the top level variable ✅ 
I ran the SDS notebook against SIT and all of the tests passed.  Nice.

**Pull request merged**
